# 显示所有配置信息
macro(info)
    message("")
    message("------------------------------------------------------------------------")
    message("-- Configuring ${PROJECT_NAME} ${PROJECT_VERSION}${VERSION_SUFFIX}")
    message("------------------------------------------------------------------------")
    message("-- CMake                Cmake version and location   ${CMAKE_VERSION} (${CMAKE_COMMAND})")
    message("-- Compiler             C++ compiler version         ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
    message("-- TARGET_PLATFORM      platform                     ${CMAKE_SYSTEM_NAME}")
    message("-- CMAKE_BUILD_TYPE     Build type                   ${CMAKE_BUILD_TYPE}")
    message("-- CMAKE_CXX_STANDARD   C++ standard                 ${CMAKE_CXX_STANDARD}")
    message("-- WITH_COVERAGE        Test code coverage           ${WITH_COVERAGE}")
    message("-- WITH_TESTS           Build and run tests          ${WITH_TESTS}")
    message("-- ORACLE_HOME          Oracle home directory        ${ORACLE_HOME}")      
    message("-- LANG                 Linux System Language        $ENV{LANG}") 
    message("-- VERSION_REVISION     Subversion revision info     ${VERSION_REVISION}") 
    message("-- COMPILE_TIME         Compile timestamp            ${COMPILE_TIME}") 
    message("-- CMAKE_DEBUG_POSTFIX  cmake debug postfix          ${CMAKE_DEBUG_POSTFIX}") 

    message("------------------------------------------------------------------------")
    message("")
endmacro()