message(STATUS)

# set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /Zi -DQT_MESSAGELOGCONTEXT")
# set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE} /DEBUG /OPT:REF /OPT:ICF")
# set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  /MP")
